[build]
  publish = "_site"
  command = "bundle exec jekyll build"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[build.environment]
  RUBY_VERSION = "3.0.0"
  NODE_VERSION = "18"