site_title: GEOVANA FOTOGRAFIA
tagline: Studio Fotográfico
hero_image: https://res.cloudinary.com/dptcrhlzf/image/upload/v1755035257/hero_f3am5y.jpg
hero_text: Capturando Momentos Únicos
meta_description: Transformo seus momentos especiais em memórias eternas através da fotografia
